Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null


Baseline_test:
    model: Baseline
    dataset_id: tiny_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    mlp1_hidden_units: [64, 32]
    mlp1_hidden_activations: relu
    mlp1_dropout: 0
    mlp1_batch_norm: False
    mlp2_hidden_units: [64, 64, 64]
    mlp2_hidden_activations: relu
    mlp2_dropout: 0
    mlp2_batch_norm: False
    use_fs: True
    fs_hidden_units: [64, 64]
    fs1_context: ["userid"]
    fs2_context: ["adgroup_id", "cate_id"]
    num_heads: 2
    batch_size: 128
    embedding_dim: 4
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

Baseline_default: # This is a config template
    model: Baseline
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    mlp1_hidden_units: [1024, 512]
    mlp1_hidden_activations: relu
    mlp1_dropout: 0
    mlp1_batch_norm: False
    mlp2_hidden_units: [1024, 512, 256]
    mlp2_hidden_activations: relu
    mlp2_dropout: 0
    mlp2_batch_norm: False
    use_fs: True
    fs_hidden_units: [1024, 512]
    fs1_context: []
    fs2_context: []
    num_heads: 2
    batch_size: 10000
    embedding_dim: 16
    epochs: 100
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
